#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 1234
#    url: jdbc:mysql://127.0.0.1:3306/books?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://127.0.0.1:3306/books?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  thymeleaf:
    cache: false
  http:
    encoding:
      charset: UTF-8
  mvc:
    date-format: yyyy-MM-dd
    static-path-pattern: /static/**
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  resources:
    static-locations: classpath:/static/

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
app:
  upload:
    location: D:/BaiduNetdiskDownload/
#    七牛云的配置

# 七牛云配置
# bucket是创建的存储空间名
# path对应存储空间的访问域名
qiniu:
  accessKey: RuRkV27BKQuVljbXAsADDD6eU45Z8VL78zT8xz1O
  secretKey: QgEsWNrHp31Rr663D1MWoUKI7SDoI-iKWCJ2lx3i
  bucket: a319test
  path: q2aio14dz.bkt.clouddn.com

baseUploadUrl: D:/BaiduNetdiskDownload/
